Drop TABLE E_LIBRARIAN

CREATE TABLE  E_BOOK 
   (	CALLNO VARCHAR(255), 
	NAME VARCHAR(255), 
	AUTHOR VARCHAR(255), 
	PUBLISHER VARCHAR(255), 
	QUANTITY int, 
	ISSUED int,
	PRIMARY KEY (CALLNO)
   )
   
   CREATE TABLE  E_LIBRARIAN
   (	ID int auto_increment, 
	NAME VARCHAR(255), 
	PASSWORD VARCHAR(255), 
	EMAIL VARCHAR(255), 
	MOBILE long,
	PRIMARY KEY (ID)
   )
   
   
   
   CREATE TABLE  E_ISSUEBOOK
   (	CALLNO VARCHAR(255) NOT NULL, 
	STUDENTID VARCHAR(255) NOT NULL, 
	STUDENTNAME VARCHAR(255), 
	STUDENTMOBILE int, 
	ISSUEDDATE DATE, 
	RETURNSTATUS VARCHAR(255)
   )